### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by david-dickinson** [hcheon549/WeTravel#1]
- [x] Remove most of the `not null` constraints in the `Users` table: Airbnb will let you create an account with just `fname`, `lname`, and `password_digest`
- [x] Replace the unique `username` with a unique `email` for account creation and logging in
- [x] No need for `location_id` foreign keys or the `Location` table - users don't need a location, and listings should have `lat` and `lng` floats to integrate with Google Maps
- [x] In the `Listings` table, `amenities` should probably be a separate table that gets joined to listings, since those are common across the site. I'd save that for a bonus, though: for now you can list amenities in the `description`
- [x] We'll use [ActiveStorage](https://github.com/appacademy/curriculum/tree/master/full-stack-project/resources/ActiveStorageDemo) to attach images to listings - that happens at the model level and in your seeds, but won't need to be reflected in your migration, so you can drop the `pictures` array
- [x] Consider giving the `Reviews` table a single foreign key for `rental_id`: you can get information about the date of the booking for the review, confirm that the user finished a stay at the listing, and submit multiple reviews for multiple stays

**Comment by hcheon549** [comment]
@david-dickinson Great help David. One other question on amenities would be to ask if I should have two tables for amenities: one for the amenities themselves and one for linking the listings and the amenities table.
