### ISSUE TITLE
Review Request: MVP 1 - Frontend Auth

### ISSUE THREAD

**Issue by hcheon549** [hcheon549/WeTravel#2]
***REMEMBER TO ASSIGN YOUR PM AS A REVIEWER**

## [Sign Up, Log In, and Demo Log In]

- [x] MVP is completely styled and seeded
- [x] MVP is bug-free with smooth navigation
- [x] MVP is bug-free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for user

- [x] [Users can sign up, sign in, log out]
- [x] [Users can use a demo login to try the site]
- [x] [Users can search for homes without logging in]
- [x] [User information bootstrapped]

### Additional Notes:
Time-permits:
1. Auto-login after clicking Demo User Log In
2. Loading image
3. Modify the style for Welcome message and log out button

**Comment by david-dickinson** [comment]
- [x] Signup form only ever renders the error "email has already been registered." Make sure to render all relevant errors.
- [x] Have the errors slice of state contain only the responseJSON - no need to expose all the rest of the error information to Redux

**Comment by hcheon549** [comment]
@david-dickinson I resolved the issues mentioned in your comments.
