### ISSUE TITLE
Review Request: MVP 2 - Listings Search by Location

### ISSUE THREAD

**Issue by hcheon549** [hcheon549/WeTravel#3]
***REMEMBER TO ADD YOUR PM AS A COLLABORATOR: Settings -> Collaborators**
***REMEMBER TO ASSIGN YOUR PM AS A REVIEWER**

## [Listings]

- [x] MVP is completely styled and seeded
- [x] MVP is bug-free with smooth navigation
- [x] MVP is bug-free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for a user
- [x] [Users can search for spots]
- [x] [Search results updates as users move Google Map]

### Additional Notes:
- Add search box feature in the index page

***_Please remember to follow markdown syntax and to delete all unnecessary lines from this template before submitting the issue_**

**Comment by david-dickinson** [comment]
- [x] Include search functionality in navbar available on the index page
- [x] Persist information on hard refresh

**Comment by hcheon549** [comment]
Fixed two features you've mentioned, @david-dickinson.
